# Generated by Django 4.1.dev20220418143310 on 2022-04-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('progresoPorcentual', models.IntegerField(max_length=200, null=True)),
                ('minutosJugados', models.IntegerField(max_length=200, null=True)),
                ('usuario', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
