# Generated by Django 4.1.dev20220418143310 on 2022-04-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_usuario_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='minutosJugados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='progresoPorcentual',
            field=models.IntegerField(null=True),
        ),
    ]
